[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  SKIP_MONGODB = "true"
  NEXT_PHASE = "phase-production-build"

# Netlify Functions Konfiguration
[functions]
  external_node_modules = []

# Testdaten-Update alle 24 Stunden um 6:00 UTC (direkte Datei-Updates)
[functions.update-test-data-daily]
  schedule = "0 6 * * *"

# Headers für bessere Performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 